"""Trading execution constants."""

from __future__ import annotations

ORDER_STATUS_PENDING_CONFIRM = "PENDING_CONFIRM"
ORDER_STATUS_SUBMITTED = "SUBMITTED"
ORDER_STATUS_PARTIAL = "PARTIAL"
ORDER_STATUS_FILLED = "FILLED"
ORDER_STATUS_CANCELED = "CANCELED"
ORDER_STATUS_REJECTED = "REJECTED"
ORDER_STATUS_FAILED = "FAILED"

ORDER_FINAL_STATUSES = {
    ORDER_STATUS_FILLED,
    ORDER_STATUS_CANCELED,
    ORDER_STATUS_REJECTED,
    ORDER_STATUS_FAILED,
}

ORDER_ACTIVE_STATUSES = {
    ORDER_STATUS_PENDING_CONFIRM,
    ORDER_STATUS_SUBMITTED,
    ORDER_STATUS_PARTIAL,
}

SIDE_BUY = "buy"
SIDE_SELL = "sell"

ORDER_TYPE_LIMIT = "limit"
ORDER_TYPE_MARKET = "market"

